services:

  db:
    image: postgres
    container_name: db
    hostname: db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db
  redis:
    container_name: redis
    image: 'redis'
    ports:
      - '6379:6379'
  
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - php
  #     - node-express
  #     - nest
  
  php:
    restart: on-failure
    container_name: php
    build: ./php
    hostname: php
    ports:
      - '8001:8001'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db
  php-swoole:
    restart: on-failure
    container_name: php-swoole
    build: ./php-swoole
    hostname: php-swoole
    ports:
      - '8010:8010'
    depends_on:
      db:
        condition: service_healthy

  node-express:
    restart: on-failure
    container_name: node-express
    build: ./node_express
    hostname: node-express
    ports:
      - '4001:4001'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db
      
  nest:
    restart: on-failure
    container_name: nest
    build: ./nest
    hostname: nest
    ports:
      - '4002:4001'
    depends_on:
      db:
        condition: service_healthy
  
  fiber:
    restart: on-failure
    container_name: fiber
    build: ./fiber
    hostname: fiber
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  golang:
    restart: on-failure
    container_name: golang
    build: ./golang
    hostname: golang
    ports:
      - '8090:8090'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db

volumes:
  db-data:

networks:
  db:

secrets:
  db-password:
    file: db/password.txt
