services:

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - monitoring
  grafana:
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    image: grafana/grafana
    container_name: grafana
    ports:
      - 4000:3000
    restart: unless-stopped
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
  
  db:
    image: postgres
    container_name: db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - monitoring
  redis:
    container_name: redis
    image: 'redis'
    ports:
      - '6379:6379'
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node-express
      - nest
  
  php:
    restart: on-failure
    container_name: php
    build: ./php
    hostname: php
    ports:
      - '81:80'
    depends_on:
      db:
        condition: service_healthy

  node-express:
    restart: on-failure
    container_name: node-express
    build: ./node_express
    hostname: node-express
    ports:
      - '8002:80'
    depends_on:
      db:
        condition: service_healthy
      
  nest:
    restart: on-failure
    container_name: nest
    build: ./nest
    hostname: nest
    ports:
      - '4001:4001'
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
  grafana_data:
  prom_data:

networks:
  monitoring:
    driver: bridge

secrets:
  db-password:
    file: db/password.txt
